"""empty message

Revision ID: f9ccc0483293
Revises: 819e4ad3a024
Create Date: 2021-11-28 01:36:52.370650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ccc0483293'
down_revision = '819e4ad3a024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_branch',
    sa.Column('accounts_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accounts_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('accounts_id', 'branch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_branch')
    # ### end Alembic commands ###
